In [1]:
import pandas as pd

In [12]:
df_shipment_tracking = pd.read_csv('shipment_tracking.csv')

In [7]:
df

        tracking_id shipment_id        status            timestamp
0                 1    dc84cc15  Order Placed  2025-06-12 02:00:00
1                 2    dc84cc15     Cancelled  2025-06-15 00:00:00
2                 3    ca536e73  Order Placed  2025-06-27 02:00:00
3                 4    ca536e73     Cancelled  2025-06-28 00:00:00
4                 5    704fa19e  Order Placed  2025-09-09 03:00:00
...             ...         ...           ...                  ...
209565       209566    3cfb7692  Order Placed  2026-02-18 04:00:00
209566       209567    3cfb7692     Picked Up  2026-02-20 00:00:00
209567       209568    f212e1c9  Order Placed  2025-11-14 01:00:00
209568       209569    f212e1c9     Picked Up  2025-11-16 00:00:00
209569       209570    f212e1c9    In Transit  2025-11-18 00:00:00

[209570 rows x 4 columns]

In [8]:
df.head()

   tracking_id shipment_id        status            timestamp
0            1    dc84cc15  Order Placed  2025-06-12 02:00:00
1            2    dc84cc15     Cancelled  2025-06-15 00:00:00
2            3    ca536e73  Order Placed  2025-06-27 02:00:00
3            4    ca536e73     Cancelled  2025-06-28 00:00:00
4            5    704fa19e  Order Placed  2025-09-09 03:00:00

In [9]:
df.tail()

        tracking_id shipment_id        status            timestamp
209565       209566    3cfb7692  Order Placed  2026-02-18 04:00:00
209566       209567    3cfb7692     Picked Up  2026-02-20 00:00:00
209567       209568    f212e1c9  Order Placed  2025-11-14 01:00:00
209568       209569    f212e1c9     Picked Up  2025-11-16 00:00:00
209569       209570    f212e1c9    In Transit  2025-11-18 00:00:00

In [10]:
df.describe()

         tracking_id
count  209570.000000
mean   104785.500000
std     60497.792294
min         1.000000
25%     52393.250000
50%    104785.500000
75%    157177.750000
max    209570.000000

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209570 entries, 0 to 209569
Data columns (total 4 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   tracking_id  209570 non-null  int64
 1   shipment_id  209570 non-null  object
 2   status       209570 non-null  object
 3   timestamp    209570 non-null  object
dtypes: int64(1), object(3)
memory usage: 6.4+ MB

In [28]:
df_shipment_tracking.isnull().sum()

tracking_id    0
shipment_id    0
status         0
timestamp      0
dtype: int64

# No null Vaules in shipment_tracking

In [13]:
df_costs = pd.read_csv('costs.csv')

In [15]:
df_costs

      shipment_id  fuel_cost  labor_cost  misc_cost
0        dc84cc15      61.08       27.24      20.75
1        ca536e73      13.74       65.13      17.63
2        704fa19e      72.68       39.47      16.84
3        aad8a598      53.69       23.23      33.16
4        e120d4ba      90.24      107.29      14.73
...           ...        ...         ...        ...
69995    33f9c844      79.98       77.36      15.16
69996    6ca403d1      53.00       95.18      36.47
69997    59a42fb4      46.60       34.45      30.81
69998    3cfb7692      23.68       26.66      12.96
69999    f212e1c9      66.42       93.76      41.10

[70000 rows x 4 columns]

In [18]:
df_costs.head()

  shipment_id  fuel_cost  labor_cost  misc_cost
0    dc84cc15      61.08       27.24      20.75
1    ca536e73      13.74       65.13      17.63
2    704fa19e      72.68       39.47      16.84
3    aad8a598      53.69       23.23      33.16
4    e120d4ba      90.24      107.29      14.73

In [19]:
df_costs.tail()

      shipment_id  fuel_cost  labor_cost  misc_cost
69995    33f9c844      79.98       77.36      15.16
69996    6ca403d1      53.00       95.18      36.47
69997    59a42fb4      46.60       34.45      30.81
69998    3cfb7692      23.68       26.66      12.96
69999    f212e1c9      66.42       93.76      41.10

In [20]:
df_costs.describe()

          fuel_cost    labor_cost     misc_cost
count  70000.000000  70000.000000  70000.000000
mean      54.977665     85.080802     27.528638
std       25.936111     37.540235     13.021547
min       10.000000     20.000000      5.000000
25%       32.550000     52.580000     16.260000
50%       54.975000     84.990000     27.580000
75%       77.422500    117.572500     38.850000
max      100.000000    149.990000     50.000000

In [21]:
df_costs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   shipment_id  70000 non-null  object
 1   fuel_cost    70000 non-null  float64
 2   labor_cost   70000 non-null  float64
 3   misc_cost    70000 non-null  float64
dtypes: float64(3), object(1)
memory usage: 2.1+ MB

In [27]:
df_costs.isnull().sum()

shipment_id    0
fuel_cost      0
labor_cost     0
misc_cost      0
dtype: int64

# No null values

In [22]:
df_courier_staff = pd.read_csv('courier_staff.csv')

In [23]:
df_courier_staff

    courier_id                name  rating vehicle_type
0     7bc57152        Justin Flynn     4.8          Van
1     87cafee3       Sherry Conrad     3.2        Truck
2     53cc593b          Joanna Liu     4.0          Car
3     c482832b        Samantha Lee     4.9          Car
4     a217d894       Carrie Santos     3.9          Van
..         ...                 ...     ...          ...
995   1bafc418     Andrea Robinson     3.9          Car
996   55f3ed49  Benjamin Middleton     3.8          Van
997   60912cf1    Michele Mcknight     4.5          Car
998   1199b2f9     Johnny Johnston     4.7        Truck
999   78434baa       Melissa Weber     3.0          Van

[1000 rows x 4 columns]

In [24]:
df_courier_staff.describe()

            rating
count  1000.000000
mean      3.998200
std       0.572647
min       3.000000
25%       3.500000
50%       4.000000
75%       4.500000
max       5.000000

In [25]:
df_courier_staff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   courier_id    1000 non-null   object
 1   name          1000 non-null   object
 2   rating        1000 non-null   float64
 3   vehicle_type  1000 non-null   object
dtypes: float64(1), object(3)
memory usage: 31.4+ KB

In [26]:
df_courier_staff.isnull().sum()

courier_id      0
name            0
rating          0
vehicle_type    0
dtype: int64

In [29]:
df_routes = pd.read_csv('routes.csv')

In [30]:
df_routes

,route_id,origin,destination,distance_km,avg_time_hours
0,fe423f38,East Victoria,South Raymond,1016.50,44.2
1,080ff620,Mooreshire,Davidshire,58.30,45.3
2,aa6e4a5f,Mooreshire,South Raymond,977.98,42.4
3,3aa7af93,Kimfort,East Johnshire,691.84,35.7
4,39913248,Tiffanyton,East David,1836.43,24.4
...,...,...,...,...,...
495,1f571fff,Mooreshire,Kimfort,1137.08,13.6
496,23d6ca93,Jonestown,East Johnshire,833.28,22.8
497,7e163bb8,West Jared,North Claudiatown,370.47,24.2
498,b76d73ec,North Christopherstad,Jasonchester,1886.07,28.7
499,26a5a0b9,New Jesse,Port Kimberly,1682.91,43.4

In [31]:
df_routes.describe()

       distance_km  avg_time_hours
count   500.000000      500.000000
mean   1052.711060       23.327000
std     567.596483       13.501202
min      50.060000        1.100000
25%     571.635000       11.600000
50%    1037.355000       22.800000
75%    1532.267500       34.900000
max    1996.100000       47.800000

In [33]:
df_routes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   route_id        500 non-null    object
 1   origin          500 non-null    object
 2   destination     500 non-null    object
 3   distance_km     500 non-null    float64
 4   avg_time_hours  500 non-null    float64
dtypes: float64(2), object(3)
memory usage: 19.7+ KB

In [35]:
df_routes.isnull().sum()

route_id          0
origin            0
destination       0
distance_km       0
avg_time_hours    0
dtype: int64

In [ ]:
# no null values in routes.csv

In [36]:
df_shipments = pd.read_json('shipments.json')

In [37]:
df_shipments

,shipment_id,order_date,origin,destination,weight,courier_id,status,delivery_date
0,dc84cc15,2025-06-12,North Dawnfort,Ginafort,43.52,b554e6a4,Cancelled,None
1,ca536e73,2025-06-27,North Williamchester,Christinechester,19.31,9b44d9ca,Cancelled,None
2,704fa19e,2025-09-09,New Colleen,West Jared,27.97,f8c3e908,Delivered,2025-09-13
3,aad8a598,2025-07-25,South Ashleystad,Jonestown,18.74,0de3fc1b,Cancelled,None
4,e120d4ba,2026-01-06,Darinton,West Jared,39.30,44def2f4,In Transit,None
...,...,...,...,...,...,...,...,...
69995,33f9c844,2025-08-09,West Jared,South Brianside,6.66,09470953,Cancelled,None
69996,6ca403d1,2025-09-05,Kimfort,East Johnshire,16.78,353f1b39,Cancelled,None
69997,59a42fb4,2025-05-29,Hollyshire,Port Sandrachester,6.97,acb241ba,Cancelled,None
69998,3cfb7692,2026-02-18,South Ashleystad,New Colleen,49.57,409aec25,Pending,None
69999,f212e1c9,2025-11-14,Tiffanyton,North Christopherstad,33.21,d1370c82,In Transit,None

In [38]:
df_shipments.describe()

             weight
count  70000.000000
mean      25.222576
std       14.287579
min        0.500000
25%       12.870000
50%       25.180000
75%       37.602500
max       50.000000

In [39]:
df_shipments.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70000 entries, 0 to 69999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   shipment_id    70000 non-null  object
 1   order_date     70000 non-null  object
 2   origin         70000 non-null  object
 3   destination    70000 non-null  object
 4   weight         70000 non-null  float64
 5   courier_id     70000 non-null  object
 6   status         70000 non-null  object
 7   delivery_date  17336 non-null  object
dtypes: float64(1), object(7)
memory usage: 4.8+ MB

In [41]:
df_shipments.isnull().sum()

shipment_id          0
order_date           0
origin               0
destination          0
weight               0
courier_id           0
status               0
delivery_date    52664
dtype: int64

In [ ]:
delivery_date    52664 has null values

In [42]:
df_warehouses = pd.read_json('warehouses.json')

In [43]:
df_warehouses

   warehouse_id                   city state  capacity
0      647a65d8      North Claudiatown    SC      9821
1      8bdbd012             East David    MT      1138
2      cfcbd086           North Justin    ND      6019
3      3bff4497     Port Sandrachester    CT      3300
4      6767e7a4   North Williamchester    SD      6822
5      fb4f0c1e    North Christianside    WI      1419
6      0647f147           North Arthur    OH      5716
7      fde209a7             Davidshire    MT      3014
8      48885907        South Brianside    WI      8819
9      eb497b1e       Christinechester    WI      7387
10     7caf8d4a           Andersonfurt    NC      3229
11     0f74ba8c          East Victoria    VA      7146
12     41b6192b          Port Kimberly    ID      6291
13     da7f8abf    West Timothychester    OH      4759
14     21a4e02c               Darinton    MA      2467
15     85c9673b            Port Ronald    AR      4498
16     9805fcb9            West Wesley    WV      3101
17     c0bb59a2       South Ashleystad    VT      7304
18     260917ca             Carolmouth    HI      3151
19     951758e8                Kimfort    OH      7926
20     b84c93ef           Robertsburgh    MI      5182
21     f3eba9d9  North Christopherstad    PA      1418
22     3d9c3505              New Jesse    CA      7331
23     696538cc       North Trevorbury    NV      6966
24     f5de23cd             South Ryan    NH      4454
25     badfd592             Pamelabury    CO      6722
26     445b5ce6            Brookeburgh    OK      3315
27     7aec3044              Jonestown    CT      6817
28     f49c722a             Tiffanyton    WV      9343
29     58df4cbf      New Patriciashire    MT      1820
30     131d4feb             West Jared    NM      9265
31     e0fe2c38       South Katiemouth    MS      6218
32     74ba985d             South John    ID      1533
33     b4622995         East Johnshire    CA      2080
34     029f2908        New Jeremyshire    HI      9549
35     6f108806        South Johnhaven    OK      1428
36     1fd957e1               Ginafort    OR      4365
37     2a1bebcd           Heathermouth    GA      8698
38     ce02458e         North Dawnfort    AK      1657
39     6581a28b       South Jacqueline    ID      7545
40     725027b4          South Raymond    SC      8378
41     89c71b15           Port Heather    NV      1360
42     29b6d374              Adammouth    CT      7976
43     c26205f3           Port Barbara    CT      3814
44     82b42412           Jasonchester    RI      4897
45     e3a2d775            Shannonview    GU      9915
46     280d966c       West Tarachester    NH      6219
47     6ee4f2f0             Hollyshire    VI      9963
48     e25788e6            New Colleen    ME      1795
49     ade45415             Mooreshire    VT      4894

In [44]:
df_warehouses.describe()

          capacity
count    50.000000
mean   5364.880000
std    2765.595641
min    1138.000000
25%    3113.500000
50%    5449.000000
75%    7373.000000
max    9963.000000

In [46]:
df_warehouses.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   warehouse_id  50 non-null     object
 1   city          50 non-null     object
 2   state         50 non-null     object
 3   capacity      50 non-null     int64
dtypes: int64(1), object(3)
memory usage: 2.0+ KB

In [47]:
df_warehouses.isnull().sum()

warehouse_id    0
city            0
state           0
capacity        0
dtype: int64

# no null values in warehouses